### PR TITLE
File uploads working with posts now. 

### PR DESCRIPTION
**Pull request by danyalr8**
## Ticket

https://github.com/CodeMonkey-Mike/selfieguess-mvp-api/issues/<ISSUE_NUMBER>

## Overview

- File uploads working with posts now. 
- Post Search by hashtags added.

## Environment

| Key         | Value                                  |
| ----------- | -------------------------------------- |
| Test URL    | http://api-staging5.mvp.selfieguess.me/graphql   |

### CODE REVIEW

**Review by phivh — CHANGES_REQUESTED** [review]
@danyalr8 please resolve conflicting files.

**Review by danyalr8 — COMMENTED** [review]
fixed

**Comment by phivh** [comment]
@danyalr8 
There are  checked functionalities, which were worked and not worked:

 ### **Worked**:
- Register
- Login
- SocialLogin
- State (Add / Delete / Get  All / Get One)
- Venue (Add / Delete / Get  All / Get One)

 ### **Not Worked**:
- Post



- User Settings



### Waiting to test:
- Comment (Add/ Delete)
- Like (Add / Delete)

cc @CodeMonkey-Mike

**Comment by phivh** [comment]
@danyalr8 
After re-check:
### Worked
- Add/Delete Comment 
- Save Settings

### Not Work
- Add post (there is no image folder to save upload file) on the server. Need to improve on it.
Screen Shot 2021-09-06 at 23 29 25

- Can't delete Post
Screen Shot 2021-09-06 at 23 23 33
 cc @CodeMonkey-Mike

**Review by CodeMonkey-Mike — APPROVED** [review]
LG!

**Pull request merged**
